[main]
HOST = '8.8.8.8'
TIMEOUT = 10
TOKEN = ""
CHAT_IDS = [0]
GROUP = 2

[schedules]

    [schedules.group1]
    Monday = []
    Tuesday = []
    Wednesday = []
    Friday = []
    Thursday = []
    Saturday = []
    Sunday = []

    [schedules.group2]
    Monday = [['00:00', '04:00'], ['08:00', '12:00'], ['16:00', '20:00'], ]
    Tuesday = [['04:00', '08:00'], ['12:00', '16:00'], ['20:00', '23:59'], ]
    Wednesday = [['00:00', '04:00'], ['08:00', '12:00'], ['16:00', '20:00'], ]
    Friday = [['04:00', '08:00'], ['12:00', '16:00'], ['20:00', '23:59'], ]
    Thursday = [['00:00', '04:00'], ['08:00', '12:00'], ['16:00', '20:00'], ]
    Saturday = [['04:00', '08:00'], ['12:00', '16:00'], ['20:00', '23:59'], ]
    Sunday = [['00:00', '04:00'], ['08:00', '12:00'], ['16:00', '20:00'], ]
